name: slack-connector
version: 0.1.0
appVersion: 0.1.0
description: "Application Connector which registers Slack APIs and Events into Kyma Service Catalog (Experimental)"
keywords:
- slack-connector
home: http://slack-connector.io/
icon: https://avatars2.githubusercontent.com/u/6911160?s=200&v=4
sources:
- https://github.com/PK85/add-ons/addons/slack-connector-0.1.0/
maintainers:
- name: PK85
