apiVersion: v1
kind: Secret
metadata:
  name: {{ template "slack-connector.fullname" . }}
  labels:
    app: {{ template "slack-connector.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    name: {{ .Values.name | quote | b64enc | quote }}
